# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Opsai.TogglyCLI
PackageVersion: 0.4.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: toggly-cli.exe
  PortableCommandAlias: toggly
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ops-ai/Toggly.FeatureManagement/releases/download/cli-v0.4.0/toggly-cli-windows-x64.zip
  InstallerSha256: cf21197f583cde65c735bcb33e0cdd7a2926bab5e8497b03892883b3f806a1ba
ManifestType: installer
ManifestVersion: 1.6.0
